name: Lint

on:
  push:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go mudule derectory
      uses: actions/checkout@v2

    - name: Install golangci-lint
      run: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.26.0
        sudo mv ./bin/golangci-lint $GOPATH/bin/

    - name: Lint
      run: golangci-lint run
